sudo: false
language: python

python: "3.6"

env:
  matrix:
   - TOXENV=py27-django110
   - TOXENV=py27-django111
   - TOXENV=py34-django110
   - TOXENV=py34-django111
   - TOXENV=py35-django110
   - TOXENV=py35-django111
   - TOXENV=py36-django111
   - TOXENV=py36-djangomaster
   - TOXENV=flake8

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35-django110
    - python: "3.5"
      env: TOXENV=py35-django111
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django110
    - python: "3.6"
      env: TOXENV=py35-django111
  allow_failures:
    - env: TOXENV=py36-djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls codacy-coverage tox

script:
  - tox

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
