sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
   - django110
   - django111
   - djangomaster
   - flake8

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.6"
      env: djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls codacy-coverage tox

script:
  - tox

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
